name: k6 Load Testing

on:
  push:
    branches:
      - '**'  # Runs on all branches
  # pull_request:
  #   branches:
  #     - main  # Runs when a PR targets the `main` branch

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Compose
        run: cd ${{ github.workspace }}/nodejs_microservice && docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start"
          sleep 30
          echo "Checking for containers..."
          docker ps

      # About to remove this step...last try..
      - name: Restart Nginx
        run: docker restart nginx-proxy

      - name: Check nginx configuration
        run: |
          docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf
          docker exec nginx-proxy nginx -t
          
      - name: Run k6 Load Test
        run: |
          cd ${{ github.workspace }}/nodejs_microservice
          docker run --network=rolldice-app-network -v $(pwd)/script.js:/k6/script.js grafana/k6 run /k6/script.js

      - name: Debug network connectivity
        run: |
          docker run --rm --network=rolldice-app-network alpine sh -c "ping -c 3 nginx-proxy"
          docker run --rm --network=rolldice-app-network alpine sh -c "wget -O- http://nginx-proxy:80 || true"
          docker run --rm --network=rolldice-app-network alpine sh -c "wget -O- http://customer:8001 || true"

      # - name: Run k6 Load Test
      #   run: |
      #     cd /home/runner/work/nodejs-microsvc/nodejs-microsvc/nodejs_microservice
      #     docker run --network=rolldice-app-network -v $(pwd)/script.js:/k6/script.js grafana/k6 run /k6/script.js

      - name: Tear down services
        run: cd ${{ github.workspace }}/nodejs_microservice && docker compose down -v

      - name: Upload k6 test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: results/

      - name: Post PR Comment on Failure
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "k6 tests failed! Check the results in the **GitHub Actions logs**."
